# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  ILD Games is the software development team that created Squatbot.
  We create open-source alternatives to modern game development software tools. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ild-games.com" # the base hostname & protocol for your site
twitter_username: ildgames
github_username:  ild-games

# Build settings
markdown: kramdown
